#配置数据源信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-001?serverTimezone=GMT%2B8
    data-username: root
    data-password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

#配置jpa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  thymeleaf:
    cache: false


